apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-run-1
  labels:
    type: test
    env: local
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step-1
            templateRef:
              name: hello-world-template
              template: say-hello
        - - name: step-2
            templateRef:
              name: hello-world-template
              template: say-hello
